### PR TITLE
Fix issue #14: don’t require afterRender for views

### PR DESCRIPTION
**Pull request by djsegal**
##### Edit:

Instead of building child link views `afterRender`, build them some time after `render`

### CODE REVIEW

**Comment by djsegal** [comment]
I'm getting the following deprecation warning, so I'm going to look more at the solution:

```
DEPRECATION: You modified (-join-classes "js-sidebar-breadcrumb cs-sidebar-breadcrumb" "ember-view" (-normalize-class "_active" view._active activeClass=undefined inactiveClass=undefined) (-normalize-class "_disabled" view._disabled activeClass=undefined inactiveClass=undefined) (-normalize-class "_transitioningIn" view._transitioningIn activeClass=undefined inactiveClass=undefined) (-normalize-class "_transitioningOut" view._transitioningOut activeClass=undefined inactiveClass=undefined)) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0 [deprecation id: ember-views.render-double-modify]
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4200/assets/vendor.js:54629:35)
        at http://localhost:4200/assets/vendor.js:22376:32
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:30851:11)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:30791:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:30785:12)
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:30853:20)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:30791:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:30785:12)
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:30853:20)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:30791:14)
```

**Comment by alexspeller** [comment]
Thanks for this, I need to spend some time checking this doesn't drastically impact performance for the non-wormhole case

**Comment by djsegal** [comment]
@alexspeller let's table it till this weekend. I need a chance to look it over again

**Comment by alexspeller** [comment]
OK great, ping me when you do

**Comment by thesubr00t** [comment]
Hi @djsegal, Any updates?

**Comment by djsegal** [comment]
@alexspeller the problem actually stemmed from a `<thead>` tag (don't ask me)

this PR still does, however, resolve the deprecation warning discussed here:
+ https://github.com/emberjs/ember.js/issues/11493

**Comment by djsegal** [comment]
Also, another good solution comes from @furkanayhan in https://github.com/emberjs/ember.js/issues/12290:

```
myMethod: function () {
  Ember.run.schedule('afterRender', this, function () {
    // some code
  }); 
}.on('init')
```

**Comment by djsegal** [comment]
@alexspeller I'm no longer running into any difficulties. 

If @thesubr00t doesn't have any more concerns, I'm ok with closing both this PR and [the issue](https://github.com/alexspeller/ember-cli-active-link-wrapper/issues/14)

**Comment by djsegal** [comment]
**closing:** pr didn't solve what it was addressing.

---

to clear my conscience, the following lines on master are a little odd and could probably be deleted: 
- https://github.com/alexspeller/ember-cli-active-link-wrapper/blob/b0744efa0533496d598582932a48fc42f59adaba/addon/mixins/active-link.js#L14-L16

**Pull request closed without merging**
