### PR TITLE
remove jquery

### PR DESCRIPTION
**Pull request by kernel-io**
as per: https://github.com/simonihmig/rfcs/blob/jquery-optional/text/0000-optional-jquery.md

### CODE REVIEW

**Comment by alexspeller** [comment]
Thanks, this looks good but the tests are failing at the moment. I don't think it's to do with your PR, I'll investigate soon

**Comment by kernel-io** [comment]
@alexspeller want me to try fix the tests?

**Comment by kernel-io** [comment]
@alexspeller want me to fix the tests?

**Comment by alexspeller** [comment]
@kernel-io sure, I'll merge this with passing tests

**Comment by kernel-io** [comment]
note to self: don't try and fix things using the github editor

@alexspeller tests are passing

**Pull request merged**
